goplus/llcppg

.github/workflows/go.yml
=> ci:fix yaml syntax err

_xtool/llcppsymg/_cmptest/parse_test/llgo.expect, _xtool/llcppsymg/_cmptest/parse_test/parse.go, _xtool/llcppsymg/args/args.go, _xtool/llcppsymg/dbg/debug.go, _xtool/llcppsymg/llcppsymg.go, _xtool/llcppsymg/parse/parse.go, _xtool/llcppsymg/symbol/symbol.go
=> invalid recv type

.github/workflows/go.yml, _llcppgtest/lua/demo/go.mod, _llcppgtest/lua/demo/hello/hello.go, _llcppgtest/lua/llcppg.cfg, cmd/llcppgtest/demo/demo.go, cmd/llcppgtest/llcppgtest.go
增加了对llcppg整体转换结果的Demo测试，对于_llcppgtest的所有子目录，都作为测试转换的用例，测试过程中，会使用llcppg读取llcppg.cfg生成转换完成的包，并通过llgo build . 验证编译，并在对应的Demo中引入该包并运行进行功能验证。
=> llcppgtest&ci: test demo with generated pkg

.github/workflows/go.yml, _llcppgtest/z3/demo/demo/demo.go, _llcppgtest/z3/llcppg.cfg
https://github.com/goplus/llcppg/issues/102
=> demo test:z3

.github/workflows/go.yml, _llcppgtest/gpgerror/demo/keyerror/keyerror.go, _llcppgtest/gpgerror/llcppg.cfg, _llcppgtest/z3/demo/demo/demo.go, cmd/gogensig/convert/_testdata/enum/conf/llcppg.cfg, cmd/gogensig/convert/_testdata/enum/gogensig.expect, cmd/gogensig/convert/_testdata/enum/hfile/temp.h, cmd/gogensig/convert/package.go
=> gogensig:remove enum item prefix

cmd/gogensig/convert/convert.go
fix https://github.com/goplus/llcppg/issues/66
=> gogensig: fix  type Struct (unnamed at /usr/local/...)

cmd/llcppgtest/demo/demo.go, cmd/llcppgtest/llcppgtest.go
```bash
lcppgtest -demos ./_llcppgtest -conf conf/macos
```
=> test:assign conf origin

_llcppgtest/libxslt/llcppg.cfg, cmd/gogensig/convert/_testdata/_depwithversion/conf/llcppg.cfg, cmd/gogensig/convert/_testdata/_depwithversion/conf/llcppg.symb.json, cmd/gogensig/convert/_testdata/_depwithversion/gogensig.expect, cmd/gogensig/convert/_testdata/_depwithversion/hfile/libxml/tree.h, cmd/gogensig/convert/_testdata/_depwithversion/hfile/libxml/xmlstring.h, cmd/gogensig/convert/_testdata/_depwithversion/hfile/temp.h, cmd/gogensig/convert/convert_test.go, cmd/gogensig/convert/deps.go
fix https://github.com/goplus/llcppg/issues/223
---
temp use https://github.com/luoliwoshang/goplus-llpkg/releases for test
=> gogensig:support load dep with version

llcppg/llcppg.go
https://github.com/goplus/llcppg/issues/217
=> llcppg:symMap & typeMap config field

_llcppgtest/cjson/conf/linux/llcppg.cfg, _llcppgtest/cjson/conf/linux/llcppg.pub, _llcppgtest/cjson/llcppg.cfg, _llcppgtest/cjson/llcppg.pub, _llcppgtest/gettext/llcppg.cfg, _llcppgtest/gettext/llcppg.pub, cmd/gogensig/convert/_testdata/cjson/conf/llcppg.cfg, cmd/gogensig/convert/_testdata/cjson/conf/llcppg.pub, cmd/gogensig/convert/_testdata/pubfile/conf/llcppg.cfg, cmd/gogensig/convert/_testdata/pubfile/conf/llcppg.pub, cmd/gogensig/convert/_testdata/pubfile/gogensig.expect, cmd/gogensig/convert/_testdata/pubfile/hfile/temp.h, cmd/gogensig/convert/convert.go, cmd/gogensig/convert/convert_test.go, cmd/gogensig/convert/deps.go
https://github.com/goplus/llcppg/issues/217
=> gogensig:load customize typeMap by llcppg.cfg instead llcppg.pub

_llcppgtest/raylib/demo/hello/demo.go
When running raylib demos in CI environments (particularly macOS), we encounter the following error:
`WARNING: GLFW: Error: 65545 Description: NSGL: Failed to find a suitable pixel format`
So we check these function which is not related to graphics initialization.
=> demo test:raylib test demo

cmd/gogensig/convert/package.go, cmd/gogensig/convert/package_test.go
panic instead output error message,when convert fail
=> gogensig:panic when convert fail

_llcppgtest/gpgerror/demo/keyerror/keyerror.go, _llcppgtest/z3/demo/demo/demo.go, cmd/gogensig/convert/_testdata/enum/gogensig.expect, cmd/gogensig/convert/_testdata/gpgerror/gogensig.expect, cmd/gogensig/convert/_testdata/xml2/gogensig.expect, cmd/gogensig/convert/package.go
for  https://github.com/goplus/llcppg/issues/298
=> gogensig:only pub enum-item instead upper camel

_xtool/llcppsymg/internal/symg/symg.go, _xtool/llcppsymg/internal/symg/symg_test.go, _xtool/llcppsymg/internal/symg/testdata/c/expect.json, _xtool/llcppsymg/internal/symg/testdata/cjson/expect.json, _xtool/llcppsymg/internal/symg/testdata/cpp/expect.json, _xtool/llcppsymg/internal/symg/testdata/gpgerror/expect.json, _xtool/llcppsymg/internal/symg/testdata/inireader/expect.json, _xtool/llcppsymg/internal/symg/testdata/isl/expect.json, _xtool/llcppsymg/internal/symg/testdata/lua/expect.json
part of https://github.com/goplus/llcppg/issues/377
=> refactor(llcppgsymg):write with json instead cjson

.github/workflows/end2end.yml, _cmptest/go.mod, _cmptest/go.sum, _cmptest/llcppgend_test.go, _cmptest/testdata/cjson/1.7.18/cjson/cJSON.go, _cmptest/testdata/cjson/1.7.18/cjson/cJSON_Utils.go, _cmptest/testdata/cjson/1.7.18/cjson/cjson_autogen_link.go, _cmptest/testdata/cjson/1.7.18/cjson/go.mod, _cmptest/testdata/cjson/1.7.18/cjson/go.sum, _cmptest/testdata/cjson/1.7.18/cjson/llcppg.pub, _cmptest/testdata/cjson/1.7.18/llcppg.cfg
a part of https://github.com/goplus/llcppg/issues/196
=> test:end2end compare test

.github/workflows/end2end.yml, .github/workflows/gentest.yml, .github/workflows/go.yml
* keep run when other matrix fail
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
=> ci:continue run when other matrix fail

.github/actions/setup-llcppg/action.yml
Fixes https://github.com/goplus/llcppg/actions/runs/15518029109/job/43703840239
=> ci: remove brew update

doc/en/dev/llcppg.md
=> doc(design):headerfile concept & dependency design

doc/en/dev/llcppg.md
part of #441  for current llcppg's design document
=> doc(design):basic name mapping rules

doc/en/dev/llcppg.md, doc/llcppg.md
=> docs(design):move headerfile example explanation

doc/en/dev/llcppg.md
=> docs(design):basic type & void *  & func pointer map

_cmptest/llcppgend_test.go, cmd/llcppgtest/demo/demo.go
Try to fix https://github.com/goplus/llcppg/actions/runs/15552842096/job/43786679058
=> fix(llcppgtest): specify GOCACHE

README.md
https://deepwiki.com/badge-maker?url=https%3A%2F%2Fdeepwiki.com%2Fgoplus%2Fllcppg
=> docs(readme):add badge to enable auto refresh deepwiki

_cmptest/cfgdata/bzip2/darwin/1.0.8/llcppg.cfg, _cmptest/cfgdata/bzip2/linux/1.0.8/llcppg.cfg, _cmptest/cfgdata/bzip3/darwin/1.5.1/llcppg.cfg, _cmptest/cfgdata/bzip3/linux/1.5.1/llcppg.cfg, _cmptest/cfgdata/cargs/darwin/1.2.0/llcppg.cfg, _cmptest/cfgdata/cargs/linux/1.2.0/llcppg.cfg, _cmptest/cfgdata/cjson/darwin/1.7.17/llcppg.cfg, _cmptest/cfgdata/cjson/darwin/1.7.18/llcppg.cfg, _cmptest/cfgdata/cjson/linux/1.7.17/llcppg.cfg, _cmptest/cfgdata/cjson/linux/1.7.18/llcppg.cfg, _cmptest/cfgdata/libtool/darwin/2.4.7/llcppg.cfg, _cmptest/cfgdata/libtool/linux/2.4.7/llcppg.cfg, _cmptest/cfgdata/libxml2/darwin/2.13.6/llcppg.cfg, _cmptest/cfgdata/libxml2/linux/2.13.6/llcppg.cfg, _cmptest/cfgdata/sqlite3/darwin/3.49.1/llcppg.cfg, _cmptest/cfgdata/sqlite3/linux/3.49.1/llcppg.cfg, _cmptest/cfgdata/zlib/darwin/1.3.1/llcppg.cfg, _cmptest/cfgdata/zlib/linux/1.3.1/llcppg.cfg, config/config.go
=> feat(llcppcfg): omit optional fields empty

cmd/llcppgtest/demo/demo.go
=> feat: copy demos to tmp dir

doc/en/dev/llcppg.md
doc for https://github.com/goplus/llcppg/issues/510
=> docs(design):function with va list should not have receiver

doc/en/dev/llcppg.md
=> docs(design): add named nested struct handling design
