goplus/llcppg

_xtool/llcppsigfetch/llcppsigfetch.go
_xtool/llcppsigfetch/parse/cvt.go
_xtool/llcppsigfetch/parse/cvt_test/cvt.go
_xtool/llcppsigfetch/parse/cvt_test/preprocess_test/llgo.expect
_xtool/llcppsigfetch/parse/cvt_test/preprocess_test/preprocess.go
_xtool/llcppsigfetch/parse/dump.go
_xtool/llcppsigfetch/parse/parse.go
_xtool/llcppsymg/clangutils/clangutils.go

* Change includes to output absolute paths for corresponding header files
* Identify system header files
* std include path
* config mode 's include flags
```json
{
"incPath": "stddef.h",
"isSys": true,
"path": "/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/stddef.h",
"doc": {
"_Type": "File",
"includes": [
{
"_Type": "Include",
"Path": "/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/_types.h"
},
{
"_Type": "Include",
"Path": "/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/_types/_size_t.h"
},
],
},
{
"incPath": "sys/_types/_size_t.h",
"path": "/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/_types/_size_t.h",
"doc": {
"_Type": "File",
"includes": [
{
"_Type": "Include",
"Path": …
```

llcppsigfetch:abs include path & system header & config mode 's include flags

---

.github/workflows/go.yml

When executing llgo cmptest ./_xtool/llcppsymg/_cmptest/... from the project root directory, an unexpected panic occurs (see [goplus/llgo#895](https://github.com/goplus/llgo/issues/895)). However, the same test command works correctly when executed directly in the ./_xtool/llcppsymg/_cmptest/ directory.

ci:llgo cmptest for llcppsifetch & llcppsymg

---

_xtool/llcppsigfetch/parse/cvt.go
_xtool/llcppsigfetch/parse/cvt_test/complex_test/forwarddecl_test/forwarddecl.go
_xtool/llcppsigfetch/parse/cvt_test/complex_test/forwarddecl_test/hfile/forwarddecl.h
_xtool/llcppsigfetch/parse/cvt_test/complex_test/forwarddecl_test/llgo.expect
cmd/gogensig/convert/package.go

fix https://github.com/goplus/llcppg/issues/38
对于 "typedef struct xxx xxx;" 这样的声明，其 underlying type 的声明位置可能出现在两个地方：
1. 当结构体是内联定义时，底层类型声明位于 typedef 内部
2. 当源文件中存在独立的 struct xxx 实现时，底层类型声明位于实现的位置
因此，我们不应该使用声明位置来判断是否需要移除额外的 Typedef 节点，而是应该使用类型名称的比较来直接进行判断。

llcppsigfetch:fix unexpect typedef decl when forward decl implement

---

_xtool/llcppsigfetch/parse/cvt_test/complex_test/forwarddecl_test/forwarddecl.go
_xtool/llcppsigfetch/parse/cvt_test/complex_test/forwarddecl_test/hfile/def.h
_xtool/llcppsigfetch/parse/cvt_test/complex_test/forwarddecl_test/hfile/impl.h
_xtool/llcppsigfetch/parse/cvt_test/complex_test/forwarddecl_test/llgo.expect
cmd/gogensig/convert/_testdata/forwarddecl/gogensig.expect
cmd/gogensig/convert/_testdata/forwarddecl/hfile/impl.h
cmd/gogensig/convert/_testdata/forwarddecl/hfile/temp.h

#48 
目前已会优先处理依赖的头文件中的类型声明实现，所以能正常转换类型实现

llcppg:cross file forward impl test case

---

_xtool/llcppsigfetch/parse/cvt.go
_xtool/llcppsigfetch/parse/cvt_test/decl_test/func_test/func.go
_xtool/llcppsigfetch/parse/cvt_test/decl_test/func_test/llgo.expect
cmd/gogensig/convert/_testdata/funcrefer/conf/llcppg.symb.json
cmd/gogensig/convert/_testdata/funcrefer/gogensig.expect
cmd/gogensig/convert/_testdata/funcrefer/hfile/temp.h

llcppsigfetch:support elaborate functype in funcdecl 

---

_xtool/llcppsigfetch/parse/cvt.go
_xtool/llcppsigfetch/parse/cvt_test/decl_test/func_test/func.go
_xtool/llcppsigfetch/parse/cvt_test/decl_test/func_test/llgo.expect
cmd/gogensig/convert/_testdata/funcrefer/conf/llcppg.symb.json
cmd/gogensig/convert/_testdata/funcrefer/gogensig.expect
cmd/gogensig/convert/_testdata/funcrefer/hfile/temp.h

fix #51 
修改获取函数声明使用已定义的函数类型时获取underlying type的方案，原先的方案通过CanonicalType获取底层类型，会导致函数类型中的所有的typedef都被desugar，导致与原函数签名不一致。
此前逻辑在获得实际函数定义时，使用了CanonicalType来获得实际typedef的函数类型，导致对于函数类型中，内部类型也做了CanonicalType的处理，从而导致获得类型时，获得的是比如 const OSSL_DISPATCH *in,实际定义的结构体类型，而不是一个类型引用，对此，获得函数的类型定义的底层类型应该通过其他方法来执行。
```
visitTop: Cursor: OSSL_provider_init_fn
ProcessTypeDefDecl: CursorName: OSSL_provider_init_fn CursorKind: TypedefDecl CursorTypeKind: Typedef
ProcessUnderlyingType: not elaborated
ProcessType: TypeName: int (const OSSL_CORE_HANDLE *, const OSSL_DISPATCH *, const OSSL_DISPATCH **, void **) TypeKind: FunctionProto
ProcessType: FunctionType  TypeName: int (const OSSL_CORE_HANDLE *, const OSSL_DISPATCH *, const OSSL_DISPATCH **, void **) TypeKind: FunctionProto
ProcessFunctionType: TypeName: int …
```

llcppsigfetch:recursive resolve typedefs to get underlying func type

---

cmd/gogensig/convert/_testdata/funcrefer/conf/llcppg.symb.json
cmd/gogensig/convert/_testdata/funcrefer/gogensig.expect
cmd/gogensig/convert/_testdata/funcrefer/hfile/temp.h
cmd/gogensig/convert/convert_test.go
cmd/gogensig/convert/package.go
cmd/gogensig/convert/package_bulitin_test.go

fix #46 
type 创建一个新类型时，其underlying必须存在，所以当typedef一个未完成类型时，其underlying不存在，对该情况则延迟加载该类型的初始化

gogensig:defer init typedef a incomplete type

---

cmd/gogensig/convert/_testdata/funcrefer/gogensig.expect
cmd/gogensig/convert/type.go

gogensig:remove extra pointer when ref defined functype (not func pointer) as param

---

cmd/gogensig/convert/_testdata/forwarddecl/conf/llcppg.symb.json
cmd/gogensig/convert/_testdata/forwarddecl/gogensig.expect
cmd/gogensig/convert/_testdata/forwarddecl/hfile/temp.h
cmd/gogensig/convert/package.go

fix #58 
之前的逻辑对于pubname和cname一致的情况下，会错误的使用空值作为新的pubname，导致不应该被提交的名称被提交了

gogensig:fix unexpect object redeined

---

cmd/gogensig/convert/_testdata/sqlite/gogensig.expect
cmd/gogensig/convert/_testdata/sqlite/hfile/sqlite3.h
cmd/gogensig/convert/names/names.go
cmd/gogensig/convert/package.go

fix #64 
对于重复的类型名添加索引的名称转换。
存在一个名称映射，用于存放cname->goname，并对于在当前工程中的类型额外存放到Pub表中

gogensig:fix same cameled type name cause panic

---

cmd/gogensig/convert/_testdata/funcrefer/conf/llcppg.symb.json
cmd/gogensig/convert/_testdata/funcrefer/gogensig.expect
cmd/gogensig/convert/_testdata/funcrefer/hfile/temp.h
cmd/gogensig/convert/_testdata/sqlite/gogensig.expect
cmd/gogensig/convert/type.go

fix #77 
修复函数签名中存在未命名和命名参数的问题，函数签名中一旦存在命名的参数，其他参数名即以参数索引作为缺省值
before 
```
func (p *Sqlite3) Exec(sql *int8, callback func(unsafe.Pointer, c.Int, **int8, **int8) c.Int, unsafe.Pointer, errmsg **int8) c.Int
```
after:
```
func (p *Sqlite3) Exec(sql *int8, callback func(unsafe.Pointer, c.Int, **int8, **int8) c.Int, __llgo_arg_2 unsafe.Pointer, errmsg **int8) c.Int
```

gogensig:ensure consistent param name in func sig

---

cmd/gogensig/convert/_testdata/forwarddecl/conf/llcppg.cfg
cmd/gogensig/convert/_testdata/forwarddecl/gogensig.expect
cmd/gogensig/convert/_testdata/forwarddecl/hfile/impl.h
cmd/gogensig/convert/_testdata/forwarddecl/hfile/temp.h
cmd/gogensig/convert/basic/basic.go
cmd/gogensig/convert/convert.go
cmd/gogensig/convert/convert_test.go
cmd/gogensig/convert/package.go
cmd/gogensig/convert/package_bulitin_test.go
cmd/gogensig/convert/package_test.go

fix #59 
- 修复存在多个向前声明不应该出现的错误输出。
- 修改文件集合遍历结束时再初始化向前声明及文件写出，以修复向前声明在被引用的文件中实现时，过早的标识为完成，导致实际的声明实现没有正确输出，

gogensig:fix unexpect redefined forward decl 's fail output

---

cmd/gogensig/convert/_testdata/receiver/conf/llcppg.cfg
cmd/gogensig/convert/_testdata/receiver/conf/llcppg.symb.json
cmd/gogensig/convert/_testdata/receiver/gogensig.expect
cmd/gogensig/convert/_testdata/receiver/hfile/temp.h
cmd/gogensig/convert/_testdata/receiver/hfile/use.h
cmd/gogensig/convert/package.go
cmd/gogensig/convert/type.go

fix https://github.com/goplus/llcppg/issues/67
* 对于处理为receiver的函数，阻止不预期的对receiver的重复获取
* 对于重复的隐式前向声明，进行复用，而不是重新创建导致重复声明
对于issue中的libcares 的redefine问题已经可以解决
```json
{
"name": "libcares",
"cflags": "$(pkg-config --cflags libcares)",
"libs": "$(pkg-config --libs libcares)",
"include": [
"ares.h",
"ares_dns_record.h"
],
"deps": null,
"trimPrefixes": [],
"cplusplus": false
}
```
仅保留预期的 /c/unix/net 没有引用的错误
```
2024/12/25 19:18:06 NewFuncDecl ares_dns_rr_set_u8 Fail: ares_dns_rr_set_u8 symbol not found
2024/12/25 19:18:06 NewFuncDecl: &{ares_dns_rr_set_u16}
2024/12/25 19:18:06 NewFuncDecl ares_dns_rr_set_u16 Fail: ares_dns_rr_set_u16 symbol not found
2024/12/25 19:18:06 NewFuncDecl: &{ares_dns_rr_set_u32}
2024/12/25 19:18:06 NewFuncDecl ares_dns_rr_set_u32 Fail: ares_dns_rr_set_u32 symbol not …
```

gogensig:fix unexpect receiver duplicate init

---

cmd/gogensig/convert/_testdata/cjson/gogensig.expect
cmd/gogensig/convert/_testdata/receiver/gogensig.expect
cmd/gogensig/convert/_testdata/sqlite/gogensig.expect
cmd/gogensig/convert/package.go
install.sh

fix p redeclared in this block

---

cmd/gogensig/convert/_testdata/cjson/conf/llcppg.pub
cmd/gogensig/convert/_testdata/cjson/gogensig.expect
cmd/gogensig/convert/_testdata/receiver/gogensig.expect
cmd/gogensig/convert/funcname.go
cmd/gogensig/convert/package.go
cmd/gogensig/convert/package_bulitin_test.go
cmd/gogensig/convert/type.go

fix #108 
* 现在的llgo:link 中的receiver的名字直接从函数签名中获取，即不会出现llgo:link 的 recevier 与函数签名的receiver不一致的情况

gogensig:link comment use same receiver in signature 

---

cmd/gogensig/convert/_testdata/forwarddecl/gogensig.expect
cmd/gogensig/convert/_testdata/receiver/gogensig.expect
cmd/gogensig/convert/_testdata/sqlite/conf/llcppg.cfg
cmd/gogensig/convert/_testdata/sqlite/gogensig.expect
cmd/gogensig/convert/_testdata/sqlite/hfile/sqlite3.h
cmd/gogensig/convert/_testdata/sqlite/hfile/sqlite3ext.h
cmd/gogensig/convert/convert.go
cmd/gogensig/convert/headerfile.go
cmd/gogensig/convert/package.go
cmd/gogensig/convert/package_bulitin_test.go
cmd/gogensig/convert/package_test.go
cmd/gogensig/convert/type.go

fix #105 
fix #104 
对于不完整类型声明，保留其文件信息，对不完整类型实现时，切换到对应文件再进行类型转换
**sqlite3** 
已经可以正常转换并调用了 https://github.com/goplus/llcppg/pull/107
**freetype2**
```go
package freetype2
import (
"github.com/goplus/llgo/c"
"unsafe"
)
type FTGlyphClass struct {
GlyphSize      FTLong
GlyphFormat    FTGlyphFormat__1
GlyphInit      unsafe.Pointer
GlyphDone      unsafe.Pointer
GlyphCopy      unsafe.Pointer
GlyphTransform unsafe.Pointer
GlyphBbox      unsafe.Pointer
GlyphPrepare   unsafe.Pointer
}
type FTGlyphClass__1 FTGlyphClass
type FTGlyphRec struct {
Library FTLibrary
Clazz   *FTGlyphClass__1
Format  FTGlyphFormat__1
Advance FTVector__1
}
```

gogensig:switch to file before complete a incomplete type

---

_xtool/llcppsymg/_cmptest/parse_test/parse.go
_xtool/llcppsymg/_cmptest/symg_test/cjson/cJSON.h
_xtool/llcppsymg/_cmptest/symg_test/cjson/llcppg.cfg
_xtool/llcppsymg/_cmptest/symg_test/inireader/INIReader.h
_xtool/llcppsymg/_cmptest/symg_test/inireader/llcppg.cfg
_xtool/llcppsymg/_cmptest/symg_test/inireader/llcppg.symb.json
_xtool/llcppsymg/_cmptest/symg_test/isl/isl/ctx.h
_xtool/llcppsymg/_cmptest/symg_test/isl/isl/polynomial.h
_xtool/llcppsymg/_cmptest/symg_test/isl/isl/polynomial_type.h
_xtool/llcppsymg/_cmptest/symg_test/isl/llcppg.cfg
_xtool/llcppsymg/_cmptest/symg_test/llgo.expect
_xtool/llcppsymg/_cmptest/symg_test/lua/llcppg.cfg
_xtool/llcppsymg/_cmptest/symg_test/lua/lua.h
_xtool/llcppsymg/_cmptest/symg_test/symg.go
_xtool/llcppsymg/dbg/debug.go
_xtool/llcppsymg/llcppsymg.go
_xtool/llcppsymg/parse/parse.go

#113 
fix #109 
* 将整体的函数信息收集逻辑，从一个文件对应一个翻译单元，修改为与llcppsigfetch一致的缓存策略，即从对于一个 a.h 为入口的翻译单元，收集其本身的函数信息，并对其include的头文件的函数符合信息一并收集，即可解决目前为了识别某个类型定义时，头文件各自为翻译单元，导致类型信息缺失的问题。
* 修改整体输入测试为文件配置输入。
```json
{
"name": "isl",
"cflags": "$(pkg-config --cflags isl)",
"libs": "$(pkg-config --libs isl)",
"include": [
"isl/polynomial.h",
"isl/polynomial_type.h",
"isl/ctx.h",
"isl/set.h",
"isl/may_type.h"
],
"trimPrefixes": ["isl_"], 
"cplusplus": false
}
```
get 
```
// llgo:link (*PwQpolynomial).PwQpolynomialGetCtx C.isl_pw_qpolynomial_get_ctx
func (recv_ *PwQpolynomial) PwQpolynomialGetCtx() *Ctx {
return nil
}
```

llcppsymg:cache file in translation unit

---

_llcppgtest/gpgerror/llcppg.cfg
_xtool/llcppsymg/_cmptest/symg_test/gpgerror/gpg-error.h
_xtool/llcppsymg/_cmptest/symg_test/gpgerror/gpgrt.h
_xtool/llcppsymg/_cmptest/symg_test/gpgerror/llcppg.cfg
_xtool/llcppsymg/_cmptest/symg_test/llgo.expect
_xtool/llcppsymg/_cmptest/symg_test/symg.go
_xtool/llcppsymg/parse/parse.go
cmd/gogensig/convert/_testdata/gpgerror/conf/llcppg.cfg
cmd/gogensig/convert/_testdata/gpgerror/conf/llcppg.symb.json
cmd/gogensig/convert/_testdata/gpgerror/gogensig.expect
cmd/gogensig/convert/_testdata/gpgerror/hfile/gpg-error.h
cmd/gogensig/convert/_testdata/gpgerror/hfile/gpgrt.h
cmd/gogensig/convert/package.go
cmd/gogensig/convert/package_bulitin_test.go

fix #106 
- 对于C语言中允许存在相同的函数实现，对于mangle name相同的函数，不视为重载，解决 https://github.com/goplus/llcppg/issues/106 中存在的两个头文件中为了兼容性，声明的相同函数被视为重载的问题
- b.修复method预期之外重复生成的问题，增加方法集检查

llcppg:allow same func decl & check methodset avoid duplicate

---

cmd/gogensig/convert/_testdata/forwarddecl/gogensig.expect
cmd/gogensig/convert/_testdata/forwarddecl/hfile/temp.h
cmd/gogensig/convert/package.go
cmd/gogensig/convert/package_bulitin_test.go

fix https://github.com/goplus/llcppg/issues/146
The problem stems from typedef-ing an incomplete type. Here's the English explanation:
The issue comes from typedef-ing an incomplete type. For incomplete types, their placeholder type initialization occurs after the entire project's conversion is complete. When typedef-ing an incomplete type, direct initialization fails because the underlying type of the incomplete type doesn't exist yet, making it impossible to construct the typedef node.
To handle this, delayed loading was implemented for typedef nodes of incomplete types. However, the problem arises when typedef-ing a node that itself is a typedef of an incomplete type (like in the example code). Since this also requires delayed loading, the same issue occurs.
```c
struct _xmlParserCtxt; …
```

gogensig:handle nested typedef of incomplete types

---

design.md

---
* llcppg 只转换本包内的头文件
* 不转换第三方包和标准库的头文件
* 对于本包头文件在处理过程中生成两类映射:
*  函数映射表 llcppg.symb.json
* 类型映射表  llcppg.pub
1. 系统扫描每个依赖包的 llcppg.pub 文件以获取类型映射.
2. 如果依赖包的 llcppg.cfg 中也包含 deps 配置，系统会递归处理这些依赖.
3. 所有依赖包的类型映射都会被加载和注册到转换工程中.
4. 在当前工程中，某个头文件中存在对于第三方包的类型的引用，即直接从当前转换工程作用域进行查找
* 如果找到映射类型，则进行引用；
* 否则提示用户缺失的类型及其来源头文件，以便用户进行转换。
每个依赖包都遵循统一的文件组织结构：（以 xml2 为例）：
* 转换完成的Go源文件
1. HTMLtree.go (由 HTMLtree.h 生成)
2. HTMLparser.go (由 HTMLparser.h 生成)
* 配置文件
1. llcppg.cfg (依赖信息)
4. llcppg.pub (类型映射信息)
```json
{
"name":"xslt",
"include": [
"libxslt/xslt.h",
"libxslt/security.h",
"libexslt/exsltconfig.h"
],
"deps": [
"c",
"github.com/goplus/..../xml2",
"github.com/goplus/..../zlib"
]
}
```
在`libxslt/xslt.h` 中依赖了 `libxml2` 的 `xmlChar` 和 `xmlNodePtr`：
```c
#include <libxml/dict.h>
#include <libxml/xmlerror.h> …
```

llcppg:cross platform & refactor deps design

---

cmd/gogensig/convert/_testdata/_depcjson/conf/llcppg.cfg
cmd/gogensig/convert/_testdata/_depcjson/hfile/temp.h
cmd/gogensig/convert/convert.go
cmd/gogensig/convert/convert_test.go
cmd/gogensig/convert/filesetprocessor/doc_fileset_processor.go
cmd/gogensig/convert/testdata/thirddep/hfile/thirddep.h
cmd/gogensig/convert/testdata/thirddep2/hfile/thirddep2.h

input in tests matches gogensig's normal input, rather than dynamically concatenating cflags when loading dependencies

gogensig:refine _depcjson test

---

cmd/gogensig/convert/convert.go
cmd/gogensig/convert/convert_test.go
cmd/gogensig/gogensig.go
cmd/llcppgtest/demo/demo.go
llcppg.go

support https://github.com/goplus/llcppg/issues/215
* llcppg -mod <module-path> determine need init a go.mod,if not specifc, dont init a new go module.
* tidy when converted end.

llcppg:-mod

---

_llcppgtest/libxml2/llcppg.cfg
cmd/gogensig/convert/_testdata/_depcjson/gogensig.expect
cmd/gogensig/convert/_testdata/_depwithversion/conf/llcppg.cfg
cmd/gogensig/convert/_testdata/_depwithversion/gogensig.expect
cmd/gogensig/convert/_testdata/_systopkg/gogensig.expect
cmd/gogensig/convert/_testdata/avoidkeyword/gogensig.expect
cmd/gogensig/convert/_testdata/cjson/gogensig.expect
cmd/gogensig/convert/_testdata/enum/gogensig.expect
cmd/gogensig/convert/_testdata/forwarddecl/gogensig.expect
cmd/gogensig/convert/_testdata/funcrefer/gogensig.expect
cmd/gogensig/convert/_testdata/gpgerror/gogensig.expect
cmd/gogensig/convert/_testdata/ignoresym/gogensig.expect
cmd/gogensig/convert/_testdata/impls/gogensig.expect
cmd/gogensig/convert/_testdata/keepcomment/gogensig.expect
cmd/gogensig/convert/_testdata/lua/gogensig.expect
cmd/gogensig/convert/_testdata/macro/gogensig.expect
cmd/gogensig/convert/_testdata/mix/gogensig.expect
cmd/gogensig/convert/_testdata/nested/gogensig.expect
cmd/gogensig/convert/_testdata/pubfile/gogensig.expect
cmd/gogensig/convert/_testdata/pubprivate/gogensig.expect
cmd/gogensig/convert/_testdata/receiver/gogensig.expect
cmd/gogensig/convert/_testdata/selfref/gogensig.expect
cmd/gogensig/convert/_testdata/sqlite/gogensig.expect
cmd/gogensig/convert/_testdata/stdtype/gogensig.expect
cmd/gogensig/convert/_testdata/union/gogensig.expect
cmd/gogensig/convert/_testdata/xml2/gogensig.expect
cmd/gogensig/convert/convert_test.go
cmd/gogensig/convert/deps.go
cmd/gogensig/convert/package.go
cmd/gogensig/convert/package_bulitin_test.go

resolved https://github.com/goplus/llcppg/issues/226
use blank import for every deps in `lib_autogen_link.go` to support indirect dep of lots of c package.
such as libxml2 ,also in header file,libxml2 not rely zlib's type,but in the runtime,with out the zlib's binaries will cause panic,llpkg need this feature to get these runtime dependency.

gogensig:gen blank import for all deps

---

cmd/gogensig/convert/_testdata/_depcjson/gogensig.expect
cmd/gogensig/convert/_testdata/_depcjson/hfile/temp.h
cmd/gogensig/convert/testdata/basicdep/basicdep.go
cmd/gogensig/convert/testdata/basicdep/hfile/basicdep.h
cmd/gogensig/convert/testdata/basicdep/llcppg.pub
cmd/gogensig/convert/testdata/thirddep/hfile/thirddep.h
cmd/gogensig/convert/testdata/thirddep/llcppg.pub
cmd/gogensig/convert/testdata/thirddep/thirddep.go

verify that depcjson can correctly reference the types from both packages, ensuring that there are no conflicts when using the same pubname.
**Handling Same pubname:**
In the basicdep package, the type `Basic_stream` is defined and mapped to `Stream`.
In the thirddep package, the type `third_dep_stream` is also defined and mapped to `Stream`.
**Output:**
A struct named `SamePubStream` has been added, which includes types with the same name from two different packages:
```go
type SamePubStream struct {
BasicStream    basicdep.Stream
ThirdDepStream thirddep.Stream
}
```

gogensig:check load same llcppg.pub's pubname

---

.github/workflows/go.yml

In Go 1.21 and earlier versions, go test would ignore packages without _test.go files when calculating test coverage. However, in Go 1.22 and later versions, go test includes all packages in the test coverage calculation, even those without test cases. Due to this change, the scope of coverage calculation has expanded, which might lead to a slight drop in coverage, as packages without tests are now also counted in the coverage statistics.

ci:update to go 1.23

---

go.mod
go.sum

https://github.com/goplus/gogen/pull/489 fix unexpect alias's zerolit
https://github.com/goplus/gogen/pull/490 support we can without `replace golang.org/x/tools => golang.org/x/tools v0.30.0` to refer a alias

deps:gogen v1.17.1

---

.github/actions/setup-llcppg/action.yml
.github/workflows/gentest.yml
.github/workflows/go.yml

This PR splits the llcppg demo tests from the unit tests, so that demo tests can begin downloading dependencies and running without having to wait for the unit tests to complete. Key changes include:
Separating the genpkg test logic into its own workflow.
Adding a composite action (setup-llcppg) to handle environment setup and dependency installation independently.
By splitting these testing processes, we aim to improve CI efficiency through parallel execution and reduce overall test duration. Please review and let me know if you have any questions or suggestions.

ci:feat: split genpkg tests to enhance speed of ci

---

cmd/gogensig/convert/_testdata/methodreturn/conf/llcppg.cfg
cmd/gogensig/convert/_testdata/methodreturn/conf/llcppg.symb.json
cmd/gogensig/convert/_testdata/methodreturn/gogensig.expect
cmd/gogensig/convert/_testdata/methodreturn/hfile/temp.h
cmd/gogensig/convert/package.go
cmd/gogensig/convert/type.go

support https://github.com/goplus/llcppg/pull/244
without this solution,will got follow situation.
this result will cause the `c` in the return type is use the `c` in the parameter,which is not have the `Int`

gogensig:return empty named struct type instead anonymous struct lit

---

cmd/gogensig/convert/_testdata/receiver/gogensig.expect
cmd/gogensig/convert/_testdata/receiver/hfile/use.h

in `cmd/gogensig/convert/_testdata/receiver/gogensig.expect.`
the `ares_addr` has gen in the temp.go

gogensig/chore:remove complete todo comment

---

_xtool/llcppsymg/_cmptest/names_test/names.go
_xtool/llcppsymg/names/names.go
cmd/gogensig/convert/_testdata/gettext/conf/llcppg.cfg
cmd/gogensig/convert/_testdata/gettext/conf/llcppg.symb.json
cmd/gogensig/convert/_testdata/gettext/gogensig.expect
cmd/gogensig/convert/_testdata/gettext/hfile/gettext-po.h
cmd/gogensig/convert/_testdata/lua/conf/llcppg.cfg
cmd/gogensig/convert/_testdata/lua/gogensig.expect
cmd/gogensig/convert/_testdata/redefine/conf/llcppg.cfg
cmd/gogensig/convert/_testdata/redefine/conf/llcppg.symb.json
cmd/gogensig/convert/_testdata/redefine/gogensig.expect
cmd/gogensig/convert/_testdata/redefine/hfile/temp.h
cmd/gogensig/convert/package.go
cmd/gogensig/convert/package_test.go

* 为了批处理的正确，优先保证对于重复命名的函数panic。
*  为了让panic正常运行，并且ci正常通过, _llcppgtest 存在用例gpgerror,这个库中存在两个几乎相同的头文件，并且没有头文件守卫，也就是对于一个头文件中会出现多个相同名称的节点，这在当前逻辑以及Go语法中是不允许的，但是在C语言中是允许的，所以为了让重复命名的函数正确panic，以及对于以下用例，能正常的通过编译，于是将经过处理的节点收集起来，阻止反复处理。
gpg-error.h
```c
/* The error value type gpg_error_t.  */
/* We would really like to use bit-fields in a struct, but using
* structs as return values can cause binary compatibility issues, in
* particular if you want to do it efficiently (also see
* -freg-struct-return option to GCC).  */
typedef unsigned int gpg_error_t;
/* We use the lowest 16 bits of gpg_error_t for error codes.  The 16th
* bit indicates system errors.  */
#define GPG_ERR_CODE_MASK	(GPG_ERR_CODE_DIM - 1)
```
gpgrt.h
```c

/* The error value type gpg_error_t.  */
/* We would really like to use …
```

gogensig:panic when func name used & skip processed node

---

_xtool/llcppsigfetch/parse/cvt.go
_xtool/llcppsigfetch/parse/cvt_test/decl_test/typedef_test/llgo.expect
_xtool/llcppsigfetch/parse/cvt_test/decl_test/typedef_test/typedef.go
cmd/gogensig/convert/convert_builtin_test.go
cmd/gogensig/convert/package_test.go

This PR fixes a bug that caused panics during typedef name processing with multi-level typedef chains where a typedef ultimately refers back to the original declaration name through intermediate typedefs.
Previously, the code only detected direct self-references in typedefs (e.g., `typedef struct Foo Foo;`), but failed to detect cases where the reference occurred through one or more intermediate typedefs:
```c
typedef enum algorithm {
UNKNOWN = 0,
NULL = 1,
} algorithm_t;
typedef algorithm_t algorithm;  // This causes a panic when processed
```
When processing typedef algorithm_t algorithm;, the system didn't recognize that algorithm_t eventually refers to enum algorithm, leading to duplicate definitions and causing a panic in subsequent processing phases.
Added a new recursive function …

llcppsigfetch:skip typedef multi-level self-references

---

_xtool/llcppsymg/_cmptest/names_test/llgo.expect
_xtool/llcppsymg/_cmptest/names_test/names.go
_xtool/llcppsymg/names/names.go
cmd/gogensig/convert/package.go
cmd/gogensig/convert/package_bulitin_test.go

1. Integrate name mapping into ProcessSymbol:
* The new system uses Node (including name and type) as the key to ensure that struct foo and typedef foo are treated as distinct entities.
* A map[Node]string is used to store the mapping from each node to its generated name, ensuring unique names for nodes with the same name but different types.
2. Remove the standalone nameMapper:
* nameMapper has limitations and cannot distinguish between nodes with the same name but different types.
--- 
1. 将命名映射集成到ProcessSymbol：
* 新系统使用Node(包含名称和类型)作为键，确保struct foo和typedef foo被视为不同实体
* 通过map[Node]string存储节点到生成名称的映射，为同名不同类型节点生成唯一名称
2. 移除独立的nameMapper：
* nameMapper 存在局限性，无法区分不同类型节点的同名情况

gogensig/refactor:collect name map by node

---

cmd/gogensig/convert/package.go
cmd/gogensig/convert/package_bulitin_test.go
cmd/gogensig/convert/package_test.go

follow is valid,but current panic.
```
struct isl_arg_choice {
const char *name;
unsigned value;
};
enum isl_arg_type {
// ....
isl_arg_choice
// ....
};
```
The isl_arg_choice as an enum item is still checked for whether its cname is in the current scope, used to submit a cname -> pubnamed type. However, for enum values, they exist as constant values and are not referenced as types in the code (e.g., syntax like isl_arg_choice x is invalid). Therefore, during the conversion process, we do not need to check the origin name of macros and enum items, but only verify their converted pubname.

gogensig:lookup origin name for type decl

---

cl/internal/convert/_testdata/_depcjson/conf/llcppg.cfg
cl/internal/convert/_testdata/_depcjson/gogensig.expect
cl/internal/convert/convert_test.go
cl/internal/convert/package_test.go
cl/internal/convert/testdata/invaliddep/llcppg.cfg
cl/internal/convert/testdata/thirddep/llcppg.cfg
cl/internal/convert/testdata/thirddep2/llcppg.cfg
cl/internal/convert/testdata/thirddep2/thirddep2.go

```
go: module github.com/goplus/llcppg@upgrade found (v0.3.1), but does not contain package github.com/goplus/llcppg/cl/internal/convert/testdata/cjson
```

cl/fix:test deps internal/convert's pkg

---

cl/nc/ncimpl/ncimpl.go

avoid collect anony enumtype to `locMap`
```json
{
"_Type":	"EnumTypeDecl",
"Loc":	{
"_Type":	"Location",
"File":	"/usr/include/aarch64-linux-gnu/bits/confname.h"
},
"Doc":	null,
"Parent":	null,
"Name":	null,
"Type":	{"..."}
}
```

cl/nc:only record third type which have name

---

.github/workflows/go.yml
_xtool/internal/parser/parser_test.go

can exit expect when llgo test
https://github.com/goplus/llcppg/actions/runs/15177637874/job/42680771642?pr=364
https://github.com/goplus/llcppg/actions/runs/15177637874/job/42680866353?pr=364
```bash
Run # llgo test ./_xtool/internal/parser/...
todo: unknown builtin type: Ibm128
--- FAIL: TestBuiltinType (0.02s)
???:1: Void Kind mismatch:got 0 want 1, 
FAIL
/home/runner/go/bin/parser.test: exit code 1
llgo test fail
Error: Process completed with exit code 1.
```

ci:check llgo test's stderr to exit

---

cmd/gogensig/unmarshal/unmarshal_test.go
internal/unmarshal/unmarshal.go
internal/unmarshal/unmarshal_test.go

https://github.com/goplus/llcppg/issues/92
* Standardize the unmarshalling behavior for a field with a null value to return nil.
* panic when unmarshal fail,because this unmarshal in a atomic ability ,not belong gogensig

internal/unmarshal:unmarshal null

---

.github/workflows/end2end.yml
_cmptest/llcppgend_test.go
cmd/gogensig/gogensig.go

resolve https://github.com/goplus/llcppg/issues/393
* log $platform-$arch-llcppg-$pkgname/$version.log to $LLCPPG_TEST_LOG_DIR or tempdir
* parallel test
expect fail   [3ac42c8](https://github.com/goplus/llcppg/pull/400/commits/3ac42c877ed4fdd679af3e99b0ec1e5e31587ec6) action https://github.com/goplus/llcppg/actions/runs/15410360485/job/43360893162?pr=400

test(e2etest):log2file & test parallel

---

_xtool/llcppsymg/internal/symg/parse.go
_xtool/llcppsymg/internal/symg/symg.go
_xtool/llcppsymg/internal/symg/symg_test.go

* process with the combine file witch contain every include file instead every file with a unit
* we can avoid reduant logic to avoid reprocess file ,because the header file guard can correct avoid
* more correct context like llcppsigfetch

refactor(llcppsymg):process by single unit

---

_xtool/llcppsymg/internal/symg/symg.go

* avoid nm list unuse symbol
* without -g libxslt got `ParseDylibSymbols: 3710 symbols` & with the -g we can got `ParseDylibSymbols: 2272 symbols` which is filter local symbol

feat(symg):avoid list not global symbol

---

_xtool/llcppsymg/internal/symg/parse.go
_xtool/llcppsymg/internal/symg/symg.go
_xtool/llcppsymg/internal/symg/symg_test.go

Since `dylibPaths` is a collection of accessible paths, duplicate checks are not required.

refactor(llcppsymg):ignore unnessary error path check

---

_cmptest/testdata/libxml2/2.13.6/libxml2/debugXML.go
_cmptest/testdata/libxml2/2.13.6/libxml2/encoding.go
_cmptest/testdata/libxml2/2.13.6/libxml2/parser.go
_cmptest/testdata/libxml2/2.13.6/libxml2/tree.go
_cmptest/testdata/libxml2/2.13.6/libxml2/valid.go
_cmptest/testdata/libxml2/2.13.6/libxml2/xlink.go
_cmptest/testdata/libxml2/2.13.6/libxml2/xpath.go
_cmptest/testdata/libxslt/1.1.42/libxslt/xsltInternals.go
_cmptest/testdata/zlib/1.3.1/zlib/zlib.go
cl/internal/convert/_testdata/funcrefer/gogensig.expect
cl/internal/convert/type.go
cmd/gogensig/testdata/lua/gogensig.expect

feat(cl):implement normal refer func pointer instead c.Pointer

---

_cmptest/testdata/libtool/2.4.7/libtool/lt_dlloader.go
_cmptest/testdata/libxml2/2.13.6/libxml2/debugXML.go
_cmptest/testdata/libxml2/2.13.6/libxml2/encoding.go
_cmptest/testdata/libxml2/2.13.6/libxml2/parser.go
_cmptest/testdata/libxml2/2.13.6/libxml2/tree.go
_cmptest/testdata/libxml2/2.13.6/libxml2/valid.go
_cmptest/testdata/libxml2/2.13.6/libxml2/xlink.go
_cmptest/testdata/libxml2/2.13.6/libxml2/xpath.go
_cmptest/testdata/libxslt/1.1.42/libxslt/xsltInternals.go
_cmptest/testdata/zlib/1.3.1/zlib/zlib.go
cl/internal/convert/_testdata/funcrefer/gogensig.expect
cl/internal/convert/type.go
cmd/gogensig/testdata/lua/gogensig.expect

feat(cl):normal refer func pointer instead

---

cl/internal/convert/package_test.go
config/config.go
config/error.go

According to the https://github.com/uber-go/guide/blob/master/style.md#error-types
Since this is a static error message that needs error matching (used with errors.Is), errors.New is the recommended approach over `fmt.Errorf`.

chore(style): refine some error name

---

_xtool/internal/parser/parser.go
_xtool/internal/parser/parser_test.go
_xtool/internal/parser/testdata/struct/temp.h

fix(parser): anonymous struct behavior when `isCpp` is false​​

---

README.md
doc/en/dev/llcppg.md

- Fix missing spaces after commas in JSON examples and text
- Fix missing spaces after colons in JSON configuration examples  
- Improve readability of English documentation
- README.md: Fix comma and colon spacing in JSON examples and text
- doc/en/dev/llcppg.md: Fix comma and colon spacing throughout
- doc/en/dev/llcppcfg.md: No changes needed (already properly formatted)
Part of #552

Fix punctuation spacing in English documentation

---

doc/en/dev/llcppg.md

docs: add nested enum
